# Generated by Django 4.1.2 on 2022-12-20 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_funcionario', models.CharField(max_length=45)),
                ('nombre_funcionario', models.CharField(max_length=45)),
                ('especialidad', models.CharField(max_length=45)),
                ('user', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_at',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atencion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mascota', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(max_length=45)),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPVET.raza')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPVET.tipo_m')),
            ],
        ),
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_cliente', models.CharField(max_length=45)),
                ('nombre_cliente', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('fono', models.CharField(max_length=45)),
                ('nombre_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPVET.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPVET.tipo_at')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elclientexd', to='APPVET.clientes')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPVET.funcionarios')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPVET.mascota')),
            ],
        ),
    ]
