# Generated by Django 4.1.2 on 2022-12-20 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPVET', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionarios',
            name='password',
        ),
        migrations.RemoveField(
            model_name='funcionarios',
            name='user',
        ),
    ]
